-- ============================================================
-- Seed: Templates de Tarefas (baseado no Advbox)
-- Clientes: '30' e '300'
-- ============================================================

INSERT INTO public.task_templates (client_id, title, points, category, color, is_active)
SELECT c.client_id, t.title, t.points, t.category, t.color, true
FROM (VALUES ('30'), ('300')) AS c(client_id)
CROSS JOIN (VALUES

  -- ── Todas ───────────────────────────────────────────────────
  ('(ADVOGADA) ANÁLISE DO CASO',                                          0,   'Todas',             '#64748b'),
  ('(ADVOGADA) REUNIÃO DE ATENDIMENTO PRESENCIAL',                        0,   'Todas',             '#64748b'),
  ('(CONTROLADORIA) REUNIÃO COM ADVOGADO PARCEIRO',                       45,  'Todas',             '#64748b'),
  ('1. PERÍCIA MÉDICA AGENDAR E AVISAR CLIENTE NO DIA QUE AGENDAR',       15,  'Todas',             '#64748b'),
  ('1. PERÍCIA SOCIAL AGENDAR E AVISAR CLIENTE NO DIA QUE AGENDAR',       15,  'Todas',             '#64748b'),
  ('2. PERÍCIA - 5 DIAS ANTES: MEET PARA ORIENTAR CLIENTE',               30,  'Todas',             '#64748b'),
  ('3. PERÍCIA - 1 DIA ANTES: LEMBRAR CLIENTE',                           4,   'Todas',             '#64748b'),
  ('4. DIA DA PERÍCIA: LIGAR PARA CLIENTE APÓS PERÍCIA',                  8,   'Todas',             '#64748b'),
  ('ALTERAR SENHA GOV (IMPRIMIR DOCUMENTAÇÃO, ALTERAR PROVISÓRIA, INCLUIR NO ADVBOX)', 30, 'Todas', '#64748b'),
  ('ANALISAR BENEFÍCIO INDEFERIDO',                                        30,  'Todas',             '#64748b'),
  ('ANALISAR CRM COM EQUIPE (30 MINUTOS)',                                 60,  'Todas',             '#64748b'),
  ('ANEXAR LAUDO NO PROCESSO',                                             4,   'Todas',             '#64748b'),
  ('ATENDIMENTO AO CLIENTE - PRESENCIAL',                                  50,  'Todas',             '#64748b'),
  ('ATUALIZAR ANOTAÇÕES GERAIS',                                           30,  'Todas',             '#64748b'),
  ('ATUALIZAR CADASTRO DO CLIENTE',                                        1,   'Todas',             '#64748b'),
  ('CARTA CLIENTE NÃO RESPONDE',                                           4,   'Todas',             '#64748b'),
  ('CRIAÇÃO DE MODELOS DE DOCUMENTOS',                                     120, 'Todas',             '#64748b'),
  ('DILIGÊNCIA EM ORGÃO PÚBLICO',                                          120, 'Todas',             '#64748b'),
  ('ELABORAR PETIÇÃO INICIAL',                                             300, 'Todas',             '#64748b'),
  ('ELABORAR PROCURAÇÃO',                                                  8,   'Todas',             '#64748b'),
  ('ENVIAR NOTIFICAÇÃO PARA CLIENTE',                                      15,  'Todas',             '#64748b'),
  ('FECHAR PARCERIA COM MÉDICO OU CLÍNICA',                                300, 'Todas',             '#64748b'),
  ('ACOMPANHAR GERID',                                                     15,  'Todas',             '#64748b'),
  ('INFORMAR CLIENTE DA PERÍCIA AGENDADA',                                 15,  'Todas',             '#64748b'),
  ('INFORMAR O CLIENTE DA DECISÃO',                                        15,  'Todas',             '#64748b'),
  ('JUNTAR DOCUMENTOS/PETIÇÃO NO PROCESSO',                                15,  'Todas',             '#64748b'),
  ('LEMBRETE DE AUDIÊNCIA D-2',                                            4,   'Todas',             '#64748b'),
  ('LIGAR (NÃO RESPONDE)',                                                 4,   'Todas',             '#64748b'),
  ('LIGAR PARA SOLICITAR LAUDO MÉDICO',                                    8,   'Todas',             '#64748b'),
  ('ORGANIZAR DOCUMENTOS ADVBOX',                                          10,  'Todas',             '#64748b'),
  ('ORGANIZAR PROCESSOS E TAREFAS - ADRIELLY',                             120, 'Todas',             '#64748b'),
  ('ORGANIZAR PROCESSOS E TAREFAS - ADRIELE',                              120, 'Todas',             '#64748b'),
  ('ORGANIZAR PROCESSOS E TAREFAS - ANA LUIZA',                            120, 'Todas',             '#64748b'),
  ('ORGANIZAR PROCESSOS E TAREFAS - FINANCEIRO',                           120, 'Todas',             '#64748b'),
  ('ORGANIZAR PROCESSOS E TAREFAS - GABRIELLA',                            120, 'Todas',             '#64748b'),
  ('ORGANIZAR PROCESSOS E TAREFAS - RAQUEL',                               120, 'Todas',             '#64748b'),
  ('ORGANIZAR PROCESSOS E TAREFAS - ROSIELE',                              120, 'Todas',             '#64748b'),
  ('PETIÇÃO SIMPLES',                                                      50,  'Todas',             '#64748b'),
  ('REUNIÃO COM ADVOGADO (LAUDO)',                                          45,  'Todas',             '#64748b'),
  ('REUNIÃO COM CLIENTE POR VÍDEO',                                        50,  'Todas',             '#64748b'),
  ('REUNIÃO DE EQUIPE',                                                    0,   'Todas',             '#64748b'),
  ('SOLICITAR DOCUMENTOS',                                                 4,   'Todas',             '#64748b'),
  ('VISITA EM DOMICÍLIO (MOTO UBER / MOTO TAXI)',                          0,   'Todas',             '#64748b'),
  ('VISITA EM DOMICÍLIO (NATAL)',                                          240, 'Todas',             '#64748b'),

  -- ── Judicial ────────────────────────────────────────────────
  ('(ADVOGADA) ANALISAR BENEFÍCIO INDEFERIDO JUDICIAL',                    0,   'Judicial',          '#3b82f6'),
  ('(ADVOGADA) ANALISAR SENTENÇA JUDICIAL',                                0,   'Judicial',          '#3b82f6'),
  ('(ADVOGADA) ELABORAR INICIAL',                                          0,   'Judicial',          '#3b82f6'),
  ('(ADVOGADA) EMENDA À INICIAL',                                          0,   'Judicial',          '#3b82f6'),
  ('ACOMPANHAR CITAÇÃO',                                                   4,   'Judicial',          '#3b82f6'),
  ('ACOMPANHAR DECISÃO/DESPACHO',                                          4,   'Judicial',          '#3b82f6'),
  ('ACOMPANHAR TRÂNSITO EM JULGADO',                                       4,   'Judicial',          '#3b82f6'),
  ('AGRAVO DE INSTRUMENTO',                                                300, 'Judicial',          '#3b82f6'),
  ('ALEGAÇÕES FINAIS SIMPLES',                                             200, 'Judicial',          '#3b82f6'),
  ('ANALISAR POSSIBILIDADE DE EMBARGOS DE DECLARAÇÃO',                     45,  'Judicial',          '#3b82f6'),
  ('AUDIÊNCIA DE CONCILIAÇÃO',                                             100, 'Judicial',          '#3b82f6'),
  ('AUDIÊNCIA: D-2 INSTRUIR CLIENTE E TESTEMINHAS PARA AUDIÊNCIA',         0,   'Judicial',          '#3b82f6'),
  ('AUDIÊNCIA: D-7 LIGAR PARA CLIENTE E LEMBRAR DATA DA AUDIÊNCIA',        8,   'Judicial',          '#3b82f6'),
  ('AUDIÊNCIA: D0 ELABORAR RELATÓRIO',                                     30,  'Judicial',          '#3b82f6'),
  ('AUDIÊNCIA: LIGAR E AVISAR CLIENTE A DATA DA AUDIÊNCIA',                8,   'Judicial',          '#3b82f6'),
  ('CONTESTAÇÃO',                                                          180, 'Judicial',          '#3b82f6'),
  ('DESPACHO COM JUIZ - PRESENCIAL/BALCÃO VIRTUAL',                        100, 'Judicial',          '#3b82f6'),
  ('ELABORAR CÁLCULO SIMPLES',                                             30,  'Judicial',          '#3b82f6'),
  ('ELABORAR DECLARAÇÕES FINAIS',                                          30,  'Judicial',          '#3b82f6'),
  ('ELABORAR DECLARAÇÕES INICIAIS',                                        50,  'Judicial',          '#3b82f6'),
  ('ELABORAR PETIÇÃO INTERMEDIÁRIA',                                       240, 'Judicial',          '#3b82f6'),
  ('ELABORAR PETIÇÃO TRABALHISTA',                                         300, 'Judicial',          '#3b82f6'),
  ('ELABORAR QUESITOS',                                                    50,  'Judicial',          '#3b82f6'),
  ('ELABORAR RELATÓRIO PROCESSUAL',                                        30,  'Judicial',          '#3b82f6'),
  ('EMBARGOS DE DECLARAÇÃO',                                               180, 'Judicial',          '#3b82f6'),
  ('IMPUGNAR O LAUDO PERICIAL DESFAVORÁVEL OU FAVORÁVEL EM PARTE APÓS A JUNTADA DO LAUDO PELO PERITO', 45, 'Judicial', '#3b82f6'),
  ('INFORMAR ANDAMENTO JUDICIAL',                                          15,  'Judicial',          '#3b82f6'),
  ('PEDIDO DE CELERIDADE PROCESSUAL',                                      20,  'Judicial',          '#3b82f6'),
  ('PREPARAR TESTEMUNHAS',                                                 50,  'Judicial',          '#3b82f6'),
  ('PROTESTO ANTI PRECLUSIVO',                                             30,  'Judicial',          '#3b82f6'),
  ('PROTOCOLAR INICIAL',                                                   120, 'Judicial',          '#3b82f6'),
  ('RECURSO ORDINÁRIO',                                                    150, 'Judicial',          '#3b82f6'),
  ('RÉPLICA/IMPUGNAÇÃO À CONTESTAÇÃO',                                     110, 'Judicial',          '#3b82f6'),

  -- ── Administrativo ──────────────────────────────────────────
  ('A1 PROTOCOLAR: PROTOCOLAR REQUERIMENTO',                               250, 'Administrativo',    '#f97316'),
  ('A2 PROTOCOLADO SEM LAUDO: PROVIDENCIAR LAUDO MÉDICO',                  8,   'Administrativo',    '#f97316'),
  ('A3 EM ANÁLISE (INSS): INFORMAR ANDAMENTO E PEDIR INDICAÇÃO (RECORRENTE 7D)', 15, 'Administrativo', '#f97316'),
  ('A4 EM EXIGÊNCIA (INSS): ANALISAR EXIGÊNCIA',                          15,  'Administrativo',    '#f97316'),
  ('A5 (ADVOGADA) CONCLUSO INDEFERIDO: ANALISAR BENEFÍCIO INDEFERIDO NO ADMINISTRATIVO', 0, 'Administrativo', '#f97316'),
  ('A5 (FLÁVIA) CONCLUSO INDEFERIDO: ANALISAR BENEFÍCIO INDEFERIDO NO ADMINISTRATIVO',  60, 'Administrativo', '#f97316'),
  ('A5 CONCLUSO CONCEDIDO: MOVER PARA FINANCEIRO',                         0,   'Administrativo',    '#f97316'),
  ('ELABORAR PETIÇÃO DE ACORDO',                                           30,  'Administrativo',    '#f97316'),
  ('RECURSO ADMINISTRATIVO',                                               120, 'Administrativo',    '#f97316'),

  -- ── Negociação ──────────────────────────────────────────────
  ('1 QUALIFICADO: EMITIR E ENVIAR CONTRATO PARA ASSINATURA',              0,   'Negociação',        '#8b5cf6'),
  ('2 COLETA DE DOCUMENTOS: ORGANIZAR DOSSIÊ E ATUALIZAR CADASTRO',        0,   'Negociação',        '#8b5cf6'),
  ('3 CONTRATO ASSINADO: SOLICITAR DOSSIÊ DE DOCUMENTOS AO CLIENTE',       0,   'Negociação',        '#8b5cf6'),
  ('4 AGENDAR COM ADVOGADO: AGENDAR REUNIÃO TÉCNICA DE VALIDAÇÃO',         0,   'Negociação',        '#8b5cf6'),
  ('5 REUNIÃO VIDEO CHAMADA (ADVOGADO E CLIENTE)',                          0,   'Negociação',        '#8b5cf6'),
  ('6 CONTRATO FECHADO: VALIDADO PELA ADVOGADA COM DOCUMENTOS',            450, 'Negociação',        '#8b5cf6'),

  -- ── Rh/financeiro ───────────────────────────────────────────
  ('$ 1/6 CONCESSÃO: INFORMAR CLIENTE DA CONCESSÃO DO BENEFÍCIO',          15,  'Rh/financeiro',     '#10b981'),
  ('$ 2/6 CONCESSÃO D-7: CONTRATAR CORRESPONDENTE PARA BANCO',             45,  'Rh/financeiro',     '#10b981'),
  ('$ 3/6 CONCESSÃO D-3: CONFERIR CARTA DE CONCESSÃO E EXTRATO DE PAGAMENTO E ENVIAR PARA CORRESPONDENTE', 25, 'Rh/financeiro', '#10b981'),
  ('$ 4/6 CONCESSÃO D-1: CONFIRMAR COM CORRESPONDENTE E CLIENTE',          0,   'Rh/financeiro',     '#10b981'),
  ('$ 5/6 CONCESSÃO D0: ARMAZENAR COMPROVANTE DE PAGAMENTO E REGISTRAR RECEBIMENTO FINANCEIRO', 10, 'Rh/financeiro', '#10b981'),
  ('$ 6/6 CONCESSÃO D0: ACOMPANHAR CORRESPONDENTE / CLIENTE',              180, 'Rh/financeiro',     '#10b981'),
  ('AÇÃO DE EXECUÇÃO DE HONORÁRIOS ADVOCATÍCIOS (EXCETO BPC)',              60,  'Rh/financeiro',     '#10b981'),
  ('ACOMPANHAR CANCELAMENTO DO BENEFÍCIO',                                 0,   'Rh/financeiro',     '#10b981'),
  ('ACOMPANHAR CLIENTE NO BANCO (CORRESPONDENTE)',                          500, 'Rh/financeiro',     '#10b981'),
  ('CARTA DE COBRANÇA EXTRAJUDICIAL',                                      8,   'Rh/financeiro',     '#10b981'),
  ('EFETUAR PAGAMENTO',                                                    10,  'Rh/financeiro',     '#10b981'),
  ('FIN D+1 VERIFICAR RECEBIMENTOS DO DIA ANTERIOR',                       8,   'Rh/financeiro',     '#10b981'),
  ('LIGAÇÃO DE COBRANÇA NO DIA DO VENCIMENTO',                             15,  'Rh/financeiro',     '#10b981'),
  ('ORGANIZAR CONTAS A PAGAR',                                             30,  'Rh/financeiro',     '#10b981'),
  ('PAGAR GUIA AVULSA',                                                    120, 'Rh/financeiro',     '#10b981'),
  ('RH: CADASTRAR COLABORADOR',                                            4,   'Rh/financeiro',     '#10b981'),
  ('RH: ENVIAR DOCUMENTO PARA ASSINATURA',                                 4,   'Rh/financeiro',     '#10b981'),
  ('RH: FAZER ADMISSÃO DE COLABORADOR',                                    50,  'Rh/financeiro',     '#10b981'),
  ('SOLICITAR PRORROGAÇÃO DE BENEFÍCIO POR INCAPACIDADE TEMPORÁRIA (AUXÍLIO-DOENÇA)', 45, 'Rh/financeiro', '#10b981'),
  ('VERIFICAR PAGAMENTOS',                                                 15,  'Rh/financeiro',     '#10b981'),
  ('VISITA COBRANÇA EM DOMICÍLIO (MOTO)',                                  300, 'Rh/financeiro',     '#10b981'),

  -- ── Recursal ────────────────────────────────────────────────
  ('ACOMPANHAR DECISÃO/ACÓRDÃO',                                           20,  'Recursal',          '#ef4444'),
  ('AGRAVO DE INSTRUMENTO (RECURSAL)',                                      100, 'Recursal',          '#ef4444'),
  ('AGRAVO DE PETIÇÃO',                                                    150, 'Recursal',          '#ef4444'),
  ('AGRAVO INTERNO',                                                       100, 'Recursal',          '#ef4444'),
  ('AVISAR CLIENTE DA DATA DA SUSTENTAÇÃO ORAL',                           10,  'Recursal',          '#ef4444'),
  ('CONTRARRAZÕES AO RECURSO ESPECIAL',                                    240, 'Recursal',          '#ef4444'),
  ('CONTRARRAZÕES AO RECURSO INOMINADO',                                   240, 'Recursal',          '#ef4444'),
  ('ELABORAR CONTRARRAZÕES',                                               240, 'Recursal',          '#ef4444'),
  ('EMBARGOS DE DECLARAÇÃO (RECURSAL)',                                     50,  'Recursal',          '#ef4444'),
  ('EMBARGOS INFRINGENTES',                                                100, 'Recursal',          '#ef4444'),
  ('EMBARGOS NO TST',                                                      300, 'Recursal',          '#ef4444'),
  ('PREPARAR SUSTENTAÇÃO ORAL',                                            100, 'Recursal',          '#ef4444'),
  ('RECURSO ADESIVO',                                                      100, 'Recursal',          '#ef4444'),
  ('RECURSO DE APELAÇÃO',                                                  120, 'Recursal',          '#ef4444'),
  ('RECURSO DE REVISTA',                                                   200, 'Recursal',          '#ef4444'),
  ('RECURSO ESPECIAL',                                                     150, 'Recursal',          '#ef4444'),
  ('RECURSO EXTRAORDINÁRIO',                                               150, 'Recursal',          '#ef4444'),
  ('RECURSO EXTRAORDINÁRIO (STF)',                                          300, 'Recursal',          '#ef4444'),
  ('RECURSO INOMINADO',                                                    120, 'Recursal',          '#ef4444'),
  ('SUSTENTAÇÃO ORAL TRT TRF TJ',                                          180, 'Recursal',          '#ef4444'),
  ('SUSTENTAÇÃO ORAL TST STJ STF',                                         200, 'Recursal',          '#ef4444'),

  -- ── Execução/cobrança ───────────────────────────────────────
  ('ACOMPANHAR IMPLANTAÇÃO DO BENEFÍCIO INSS - DIÁRIA [AGUARDANDO IMPLANTAÇÃO INSS]', 8, 'Execução/cobrança', '#f59e0b'),
  ('ACOMPANHAR LIBERAÇÃO RPV (FINANCEIRO VICTORIA)',                        8,   'Execução/cobrança', '#f59e0b'),
  ('CONFERIR CÁLCULO DO PERITO/DA PARTE',                                  30,  'Execução/cobrança', '#f59e0b'),
  ('DILIGÊNCIA EM CARTÓRIO',                                               10,  'Execução/cobrança', '#f59e0b'),
  ('ELABORAR INTIMAÇÃO INSS PARA IMPLANTAR BENEFÍCIO',                     20,  'Execução/cobrança', '#f59e0b'),
  ('ELABORAR PETIÇÃO DE CUMPRIMENTO DE SENTENÇA',                          100, 'Execução/cobrança', '#f59e0b'),
  ('ELABORAR PETIÇÃO DE EXECUÇÃO',                                         100, 'Execução/cobrança', '#f59e0b'),
  ('ELABORAR PETIÇÃO DE LIQUIDAÇÃO (TRABALHISTA)',                          10,  'Execução/cobrança', '#f59e0b'),
  ('ELABORAR RESUMO DA DECISÃO PARA O INSS',                               20,  'Execução/cobrança', '#f59e0b'),
  ('EMBARGOS À EXECUÇÃO',                                                  150, 'Execução/cobrança', '#f59e0b'),
  ('EMITIR BOLETOS / RECIBO',                                              10,  'Execução/cobrança', '#f59e0b'),
  ('EXPEDIÇÃO DE ALVARÁ',                                                  30,  'Execução/cobrança', '#f59e0b'),
  ('IMPUGNAÇÃO À PENHORA',                                                 100, 'Execução/cobrança', '#f59e0b'),
  ('IMPUGNAÇÃO AO CÁLCULO',                                                100, 'Execução/cobrança', '#f59e0b'),
  ('LEVANTAMENTO DE ALVARÁ',                                               20,  'Execução/cobrança', '#f59e0b'),
  ('LEVANTAMENTO DE RPV (ADVOGADO) - CERTIDÃO DE OBJETO E PÉ',             70,  'Execução/cobrança', '#f59e0b'),
  ('RECEBER RPV COM CERTIDÃO DE OBJETO E PÉ',                              0,   'Execução/cobrança', '#f59e0b'),

  -- ── Arquivamento ────────────────────────────────────────────
  ('CANCELAR BENEFÍCIO NO INSS E ARQUIVAR PROCESSO DO ADVBOX',             30,  'Arquivamento',      '#6b7280'),

  -- ── Consultoria ─────────────────────────────────────────────
  ('CONFERÊNCIA DE AGENDA',                                                15,  'Consultoria',       '#14b8a6'),
  ('CONFERÊNCIA DE PRAZOS FATAIS',                                         45,  'Consultoria',       '#14b8a6'),
  ('PARABENIZAR ANIVERSARIANTES DO DIA',                                   15,  'Consultoria',       '#14b8a6')

) AS t(title, points, category, color)
ON CONFLICT DO NOTHING;
