-- AI model configuration per feature per client
CREATE TABLE IF NOT EXISTS public.client_ai_model_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id text NOT NULL,
  feature text NOT NULL,
  model text NOT NULL DEFAULT 'google/gemini-2.5-flash',
  updated_at timestamptz DEFAULT now(),
  UNIQUE(client_id, feature)
);

ALTER TABLE public.client_ai_model_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "client_ai_model_config open" ON public.client_ai_model_config
  FOR ALL USING (true) WITH CHECK (true);

-- Conversation summaries generated by AI
CREATE TABLE IF NOT EXISTS public.chat_conversation_summaries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  client_id text NOT NULL,
  sentiment text,
  summary text NOT NULL,
  atendimento text,
  first_message_ts timestamptz,
  last_message_ts timestamptz,
  message_count int DEFAULT 0,
  triggered_by text DEFAULT 'manual',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.chat_conversation_summaries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "chat_conversation_summaries open" ON public.chat_conversation_summaries
  FOR ALL USING (true) WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_chat_conv_summaries_conv ON public.chat_conversation_summaries(conversation_id);
CREATE INDEX IF NOT EXISTS idx_chat_conv_summaries_contact ON public.chat_conversation_summaries(contact_id);