-- AI model configuration per feature per client
CREATE TABLE IF NOT EXISTS client_ai_model_config (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id text NOT NULL,
  feature text NOT NULL,   -- 'chat_assist' | 'copilot_crm' | 'copilot_chat'
  model text NOT NULL DEFAULT 'google/gemini-2.5-flash',
  updated_at timestamptz DEFAULT now(),
  UNIQUE(client_id, feature)
);

ALTER TABLE client_ai_model_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "client_ai_model_config_client_own" ON client_ai_model_config
  USING (client_id = (SELECT raw_user_meta_data->>'client_id' FROM auth.users WHERE id = auth.uid()));

-- Conversation summaries generated by AI
CREATE TABLE IF NOT EXISTS chat_conversation_summaries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  contact_id uuid NOT NULL,
  client_id text NOT NULL,
  sentiment text,
  summary text NOT NULL,
  atendimento text,
  first_message_ts timestamptz,
  last_message_ts timestamptz,
  message_count int DEFAULT 0,
  triggered_by text DEFAULT 'manual',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE chat_conversation_summaries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "chat_conversation_summaries_client_own" ON chat_conversation_summaries
  USING (client_id = (SELECT raw_user_meta_data->>'client_id' FROM auth.users WHERE id = auth.uid()));
